import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Allura } from "next/font/google";
import GlobalProviders from "@/provider";

const inter = Inter({ subsets: ["latin"] });

const ceder = Allura({
  subsets: ["latin"],
  variable: "--font-cedarville-cursive",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${ceder.variable} bg-red-50 w-[70%] mx-auto`}
      >
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
